// Generated by https://quicktype.io

export interface Activity {
    id:          string;
    title:       string;
    date:        string;
    description: string;
    category:    string;
    city:        string;
    venue:       string;
}
